name 'haproxy'
maintainer 'Katar012 - jvilamarin31 - AlejandroRodriguezDev'
license 'RE MARICON EL QUE LO LEA'
description 'Instala y habilita el servicio HAProxy'
version '0.1.0'
chef_version '>= 16.0'
